In [12]:
!pip install -q pydot
!pip install -q pydot-ng
!pip install -q graphviz

from sklearn.datasets import load_iris
from keras.utils import plot_model
from sklearn.externals.six import StringIO
import numpy as np
from sklearn import tree
import pydot


iris = load_iris()
test_idx = [0,50,100]

print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])
print(iris.target[0])

Reading package lists... Done
Building dependency tree       
Reading state information... Done
graphviz is already the newest version (2.40.1-2).
The following package was automatically installed and is no longer required:
  libnvidia-common-410
Use 'apt autoremove' to remove it.
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0


In [2]:
for i in range(len(iris.target)):
    print("example %d: label: %s, features %s" % (i,iris.target[i],iris.data[i]))

example 0: label: 0, features [5.1 3.5 1.4 0.2]
example 1: label: 0, features [4.9 3.  1.4 0.2]
example 2: label: 0, features [4.7 3.2 1.3 0.2]
example 3: label: 0, features [4.6 3.1 1.5 0.2]
example 4: label: 0, features [5.  3.6 1.4 0.2]
example 5: label: 0, features [5.4 3.9 1.7 0.4]
example 6: label: 0, features [4.6 3.4 1.4 0.3]
example 7: label: 0, features [5.  3.4 1.5 0.2]
example 8: label: 0, features [4.4 2.9 1.4 0.2]
example 9: label: 0, features [4.9 3.1 1.5 0.1]
example 10: label: 0, features [5.4 3.7 1.5 0.2]
example 11: label: 0, features [4.8 3.4 1.6 0.2]
example 12: label: 0, features [4.8 3.  1.4 0.1]
example 13: label: 0, features [4.3 3.  1.1 0.1]
example 14: label: 0, features [5.8 4.  1.2 0.2]
example 15: label: 0, features [5.7 4.4 1.5 0.4]
example 16: label: 0, features [5.4 3.9 1.3 0.4]
example 17: label: 0, features [5.1 3.5 1.4 0.3]
example 18: label: 0, features [5.7 3.8 1.7 0.3]
example 19: label: 0, features [5.1 3.8 1.5 0.3]
example 20: label: 0, features

In [0]:
train_target = np.delete(iris.target,test_idx)
train_data = np.delete(iris.data,test_idx,axis=0)

test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

clf = tree.DecisionTreeClassifier()
clf.fit(train_data,train_target);

In [5]:
print(test_target)

[0 1 2]


In [6]:
clf.predict(test_data)

array([0, 1, 2])

In [11]:
dot_data = StringIO()
tree.export_graphviz(clf,
                    out_file=dot_data,
                    feature_names=iris.feature_names,
                    class_names=iris.target_names,
                    filled=True,rounded=True,
                    impurity=False)
graph = pydot.graph_from_dot_data(dot_data.getvalue())
#print(graph)
graph.write_pdf("iris.pdf")


AttributeError: ignored